-- =========================================
-- By Rafael Hanson - Controle de acesso pago
-- =========================================
-- Execute este script no Supabase SQL Editor.

-- 1) Tabela de usuários aprovados
create table if not exists public.approved_users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  active boolean not null default true,
  note text,
  created_at timestamptz not null default now()
);

alter table public.approved_users enable row level security;

-- Usuário logado pode apenas consultar o próprio e-mail
drop policy if exists "approved_users_self_select" on public.approved_users;
create policy "approved_users_self_select"
on public.approved_users
for select
to authenticated
using (lower(email) = lower(auth.jwt()->>'email'));

-- 2) Log de novos cadastros (para auditoria/notificação)
create table if not exists public.signup_notifications (
  id bigint generated by default as identity primary key,
  email text not null,
  user_id uuid,
  source text default 'web',
  created_at timestamptz not null default now()
);

alter table public.signup_notifications enable row level security;

-- Permite inserir log de cadastro pelo frontend autenticado/anon
drop policy if exists "signup_notifications_insert_any" on public.signup_notifications;
create policy "signup_notifications_insert_any"
on public.signup_notifications
for insert
to anon, authenticated
with check (true);

-- Apenas usuários autenticados consultam os próprios registros
drop policy if exists "signup_notifications_self_select" on public.signup_notifications;
create policy "signup_notifications_self_select"
on public.signup_notifications
for select
to authenticated
using (lower(email) = lower(auth.jwt()->>'email'));

-- 3) Exemplo: liberar um usuário manualmente
-- insert into public.approved_users (email, active, note)
-- values ('cliente@email.com', true, 'Comprador do ebook');

